- hosts: localhost
  tasks:
    - name: Install compiler's compiler tools
      become: yes
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - bison
        - curl
        - flex
        - gcc
        - gdb
        - nasm
        - make
        - pandoc
        - software-properties-common
  tags: compiler

- hosts: localhost
  tasks:
    - name: Include "{{ ansible_os_family }}." tasks
      include: "{{ ansible_os_family }}.yml" 
  tags: vscode
